# Generated by Django 5.2.3 on 2025-06-24 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_status_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.CharField(blank=True, help_text='Max 250 characters', max_length=250)),
                ('display_name', models.CharField(blank=True, help_text='Optional different name to display', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('pronouns', models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('he', 'He/Him'), ('she', 'She/Her'), ('they', 'They/Them'), ('other', 'Other pronouns')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
