# Generated by Django 5.2.3 on 2025-06-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
    ]
